# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
#cache:
#  paths:
#    - .cache/pip
#    - venv/

before_script:
  - apt-get update ; apt-get install python3-dev python3-pip -y
  - python3 -V # Print out python version for debugging
  - pip3 install cython
  - pip3 install -r requirements.txt

#test:
#  script:
#  - python setup.py test
#  - pip install tox flake8 # you can also use tox
#  - tox -e py36,flake8

build:u16cu90:
  image: stereolabs/zed:ubuntu1604-cuda9.0-zed2.8
  script:
  - python3 setup.py build
  - pip3 wheel .
  artifacts:
    paths:
    - ./*.whl
    
build:u16cu100:
  image: stereolabs/zed:ubuntu1604-cuda10.0-zed2.8
  script:
  - python3 setup.py build
  - pip3 wheel .
  artifacts:
    paths:
    - ./*.whl
    
build:u18cu100:
  image: stereolabs/zed:ubuntu1804-cuda10.0-zed2.8
  script:
  - python3 setup.py build
  - pip3 wheel .
  artifacts:
    paths:
    - ./*.whl
    
pages:
  image: stereolabs/zed:ubuntu1604-cuda9.0-zed2.8
  script:
  - python3 setup.py install
  - pip3 install sphinx sphinx-rtd-theme
  - cd doc ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
